apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-app-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: chatgpt-app
  template:
    metadata:
      labels:
        app: chatgpt-app
    spec:
      containers:
      - name: chatgpt-app
        image: yash5090/chatgpt-app:latest
        ports:
        - containerPort: 3000
